Homework2
made-ml-in-prod-2021/beranton pull request #3
Opened 2021-05-19 14:06 UTC by BerAnton

Решение второй домашки (Docker + REST)

Самооценка:
1) Инференс модели на FastAPI - 3 балла.
2) Написан тест на предикт - 3 балла.
3) Скрипт для запросов - 2 балла.
4) Валидация входных данных - 3 балла.
5) Dockerfile - 4 балла.
6) Оптимизирован размер образа - 3 балла.
7) Есть образ на dockerhub - 2 балла.
8) В README есть инструкции - 1 балл.
9) Проведена самооценка - 1 балл.
Сумма - 22 балла.

2021-05-19 14:28 UTC, biquaternion commented
Посмотрю в выходные. Если ревью нужно раньше, то поменяйте, пожалуйста, ревьюера

2021-05-23 13:20 UTC, Mikhail-M requested changes
Добейтесь, чтобы кода для первой дз тут не было

2021-05-23 21:17 UTC, biquaternion commented on online_inference/README.md
> + docker build . -f online_inference/app/Dockerfile -t predict_app:v1
Путь как будто от корня репозитория. При следовании этому readme кажется естественным выполнять команды из текущей папки. Но так не сработает
Либо надо написать, мол "...выполнить команды, находясь в корне репозитория" либо (что мне кажется правильнее) делать build из текущей папки

2021-05-23 21:21 UTC, biquaternion commented on online_inference/app/Dockerfile
> +CMD ["uvicorn", "prediction:app", "--host", "0.0.0.0", "--port", "8080"]
prediction:app у меня не запустился с ошибкой
ERROR:    Error loading ASGI app. Could not import module "prediction".
Если поправить на app:app, то запускается, но там идут питоновские исключения, например ModuleNotFoundError: No module named 'utils'
Не исключаю, что я ошибся при сборке/запуске, но действовал по readme

2021-05-23 21:38 UTC, biquaternion commented on online_inference/app/Dockerfile
> +CMD ["uvicorn", "prediction:app", "--host", "0.0.0.0", "--port", "8080"]
Если добавить ENV PYTHONPATH app, и вместо prediction:app сделать app:prediction, тогда запустится

2021-05-23 21:42 UTC, biquaternion commented on online_inference/request.py
> +        request_data = [x.item() if isinstance(x, np.generic) else x for in data.iloc[i].tolist()]
Syntax error. Не хватает x 
request_data = [x.item() if isinstance(x, np.generic) else x for **вот здесь** in data.iloc[i].tolist()]

2021-05-23 21:44 UTC, biquaternion commented on online_inference/request.py
> +@click.comman()
comman**d**

2021-05-23 21:49 UTC, biquaternion commented on online_inference/README.md
> +Для запросов к сервису написан скрипт make_request.py.
make_request.py -> request.py

2021-05-23 22:23 UTC, biquaternion requested changes
по структуре :
src/model.pkl
src/transformer.pkl
ИМХО, папка src для кода, а здесь бинарники

2021-05-23 22:23 UTC, biquaternion commented on online_inference/request.py
> +@click.option("--count", deafult=1, help="Number of data rows")
deafult -> default

2021-05-23 22:23 UTC, biquaternion commented on online_inference/app/prediction.py
> +        transformer = load_transformer(filepath)
Не хватает объявления load_transformer(s: str)

2021-06-02 13:10 UTC, BerAnton commented
merge conflict пофикшу после аппрува

2021-06-05 17:36 UTC, biquaternion commented on online_inference/request.py
> +@click.option("--count", deafault=1, help="Number of data rows")
deafault - тоже ошибка
Правильно default

2021-06-06 10:00 UTC, Mikhail-M approved these changes
Оптимизация: 1.5
Тесты: 2(так как для тестов нужен файл с моделью)

Баллы: 19.5

2021-06-06 12:13 UTC, merged